package codewars

type Theme struct {
	CardColor         string
	HeadlineFontColor string
	BodyFontColor     string
	IconColor         string
	RankBadgeColor    string
	Font              string
	GradientValues    GradientValues
}

type GradientValues struct {
	StartColor  string
	StopColor   string
	X1          string
	Y1          string
	X2          string
	Y2          string
	OffsetStart string
	OffsetStop  string
}

// If you want to add a new gradient theme, you need to add some special
// characters to the "Card" value. The format is:
// {StartColor},{StopColor},{X1},{Y1},{X2},{Y2},{OffsetStart},{OffsetStop}
// The {LEVEL} placeholder will be replaced with the color of the user's level.
// You also need to name the theme starting with "gradient" like "gradient_my_theme_name".

var Themes = map[string]Theme{
	"default": {
		CardColor:         "#262729",
		HeadlineFontColor: "#F1F5F3",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient": {
		CardColor:         "#262729,#BB432C,40,10,100,0,0,100",
		HeadlineFontColor: "#F1F5F3",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_by_level": {
		CardColor:         "#262729,{LEVEL},40,10,100,0,0,100",
		HeadlineFontColor: "#F1F5F3",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"light": {
		CardColor:         "#fffefe",
		HeadlineFontColor: "#181919",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_light": {
		CardColor:         "#fffefe,#3C7EBB,40,10,100,0,0,100",
		HeadlineFontColor: "#181919",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_light_by_level": {
		CardColor:         "#fffefe,{LEVEL},40,10,100,0,0,100",
		HeadlineFontColor: "#181919",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"dark": {
		CardColor:         "#000000",
		HeadlineFontColor: "#F1F5F3",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_dark": {
		CardColor:         "#000000,#8D8D8D,40,10,100,0,0,100",
		HeadlineFontColor: "#F1F5F3",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_dark_by_level": {
		CardColor:         "#000000,{LEVEL},40,10,100,0,0,100",
		HeadlineFontColor: "#F1F5F3",
		BodyFontColor:     "#BB432C",
		IconColor:         "#6795DE",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"highcontrast": {
		CardColor:         "#000",
		HeadlineFontColor: "#e7f216",
		BodyFontColor:     "#fff",
		IconColor:         "#00ffff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"midnight_purple": {
		CardColor:         "#000",
		HeadlineFontColor: "#9745f5",
		BodyFontColor:     "#fff",
		IconColor:         "#9f4bff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_midnight_puple": {
		CardColor:         "#000,#9745f5,40,10,100,0,0,100",
		HeadlineFontColor: "#9745f5",
		BodyFontColor:     "#fff",
		IconColor:         "#9f4bff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_midnight_puple_by_level": {
		CardColor:         "#000,{LEVEL},40,10,100,0,0,100",
		HeadlineFontColor: "#9745f5",
		BodyFontColor:     "#fff",
		IconColor:         "#9f4bff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"midnight_blue": {
		CardColor:         "#000",
		HeadlineFontColor: "#0079fa",
		BodyFontColor:     "#0079fa",
		IconColor:         "#0079fa",
		RankBadgeColor:    "#2100fa",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"purple_dark": {
		CardColor:         "#2d2b55",
		HeadlineFontColor: "#c792ea",
		BodyFontColor:     "#a599e9",
		IconColor:         "#b362ff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_purple_dark": {
		CardColor:         "#2d2b55,#c792ea,40,10,100,0,0,100",
		HeadlineFontColor: "#c792ea",
		BodyFontColor:     "#a599e9",
		IconColor:         "#b362ff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_purple_dark_by_level": {
		CardColor:         "#2d2b55,{LEVEL},40,10,100,0,0,100",
		HeadlineFontColor: "#c792ea",
		BodyFontColor:     "#a599e9",
		IconColor:         "#b362ff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"purple_light": {
		CardColor:         "#ffffff",
		HeadlineFontColor: "#a84ee5",
		BodyFontColor:     "#8c64e0",
		IconColor:         "#b362ff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_purple_light": {
		CardColor:         "#ffffff,#a84ee5,40,10,100,0,0,100",
		HeadlineFontColor: "#a84ee5",
		BodyFontColor:     "#8c64e0",
		IconColor:         "#b362ff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_purple_light_by_level": {
		CardColor:         "#ffffff,{LEVEL},40,10,100,0,0,100",
		HeadlineFontColor: "#a84ee5",
		BodyFontColor:     "#8c64e0",
		IconColor:         "#b362ff",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"nightowl": {
		CardColor:         "#011627",
		HeadlineFontColor: "#c792ea",
		BodyFontColor:     "#7fdbca",
		IconColor:         "#ffeb95",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"solarized_dark": {
		CardColor:         "#002b36",
		HeadlineFontColor: "#268bd2",
		BodyFontColor:     "#859900",
		IconColor:         "#b58900",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"solarized_light": {
		CardColor:         "#fdf6e3",
		HeadlineFontColor: "#268bd2",
		BodyFontColor:     "#859900",
		IconColor:         "#b58900",
		RankBadgeColor:    "#181919",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"dracula": {
		CardColor:         "#282a36",
		HeadlineFontColor: "#ff79c6",
		BodyFontColor:     "#f8f8f2",
		IconColor:         "#bd93f9",
		RankBadgeColor:    "#44475a",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_dracula": {
		CardColor:         "#282a36,#bd93f9,40,10,100,0,0,100",
		HeadlineFontColor: "#ff79c6",
		BodyFontColor:     "#f8f8f2",
		IconColor:         "#bd93f9",
		RankBadgeColor:    "#44475a",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"nord": {
		CardColor:         "#2e3440",
		HeadlineFontColor: "#88c0d0",
		BodyFontColor:     "#d8dee9",
		IconColor:         "#81a1c1",
		RankBadgeColor:    "#3b4252",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_nord": {
		CardColor:         "#2e3440,#5e81ac,40,10,100,0,0,100",
		HeadlineFontColor: "#88c0d0",
		BodyFontColor:     "#d8dee9",
		IconColor:         "#81a1c1",
		RankBadgeColor:    "#3b4252",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"monokai": {
		CardColor:         "#272822",
		HeadlineFontColor: "#f92672",
		BodyFontColor:     "#f8f8f2",
		IconColor:         "#a6e22e",
		RankBadgeColor:    "#1e1f1c",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_monokai": {
		CardColor:         "#272822,#f92672,40,10,100,0,0,100",
		HeadlineFontColor: "#f92672",
		BodyFontColor:     "#f8f8f2",
		IconColor:         "#a6e22e",
		RankBadgeColor:    "#1e1f1c",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gruvbox": {
		CardColor:         "#282828",
		HeadlineFontColor: "#fabd2f",
		BodyFontColor:     "#ebdbb2",
		IconColor:         "#b8bb26",
		RankBadgeColor:    "#1d2021",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_gruvbox": {
		CardColor:         "#282828,#d65d0e,40,10,100,0,0,100",
		HeadlineFontColor: "#fabd2f",
		BodyFontColor:     "#ebdbb2",
		IconColor:         "#b8bb26",
		RankBadgeColor:    "#1d2021",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gruvbox_light": {
		CardColor:         "#fbf1c7",
		HeadlineFontColor: "#9d0006",
		BodyFontColor:     "#3c3836",
		IconColor:         "#79740e",
		RankBadgeColor:    "#ebdbb2",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"tokyo_night": {
		CardColor:         "#1a1b26",
		HeadlineFontColor: "#7aa2f7",
		BodyFontColor:     "#a9b1d6",
		IconColor:         "#bb9af7",
		RankBadgeColor:    "#16161e",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_tokyo_night": {
		CardColor:         "#1a1b26,#7aa2f7,40,10,100,0,0,100",
		HeadlineFontColor: "#7aa2f7",
		BodyFontColor:     "#a9b1d6",
		IconColor:         "#bb9af7",
		RankBadgeColor:    "#16161e",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"one_dark": {
		CardColor:         "#282c34",
		HeadlineFontColor: "#61afef",
		BodyFontColor:     "#abb2bf",
		IconColor:         "#c678dd",
		RankBadgeColor:    "#21252b",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_one_dark": {
		CardColor:         "#282c34,#61afef,40,10,100,0,0,100",
		HeadlineFontColor: "#61afef",
		BodyFontColor:     "#abb2bf",
		IconColor:         "#c678dd",
		RankBadgeColor:    "#21252b",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"catppuccin_mocha": {
		CardColor:         "#1e1e2e",
		HeadlineFontColor: "#cba6f7",
		BodyFontColor:     "#cdd6f4",
		IconColor:         "#f5c2e7",
		RankBadgeColor:    "#181825",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_catppuccin_mocha": {
		CardColor:         "#1e1e2e,#cba6f7,40,10,100,0,0,100",
		HeadlineFontColor: "#cba6f7",
		BodyFontColor:     "#cdd6f4",
		IconColor:         "#f5c2e7",
		RankBadgeColor:    "#181825",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"catppuccin_latte": {
		CardColor:         "#eff1f5",
		HeadlineFontColor: "#8839ef",
		BodyFontColor:     "#4c4f69",
		IconColor:         "#ea76cb",
		RankBadgeColor:    "#dce0e8",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_catppuccin_latte": {
		CardColor:         "#eff1f5,#8839ef,40,10,100,0,0,100",
		HeadlineFontColor: "#8839ef",
		BodyFontColor:     "#4c4f69",
		IconColor:         "#ea76cb",
		RankBadgeColor:    "#dce0e8",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"synthwave": {
		CardColor:         "#262335",
		HeadlineFontColor: "#ff7edb",
		BodyFontColor:     "#f97e72",
		IconColor:         "#36f9f6",
		RankBadgeColor:    "#1e1a2e",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_synthwave": {
		CardColor:         "#262335,#ff7edb,40,10,100,0,0,100",
		HeadlineFontColor: "#ff7edb",
		BodyFontColor:     "#f97e72",
		IconColor:         "#36f9f6",
		RankBadgeColor:    "#1e1a2e",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"cobalt": {
		CardColor:         "#193549",
		HeadlineFontColor: "#ffc600",
		BodyFontColor:     "#ffffff",
		IconColor:         "#0088ff",
		RankBadgeColor:    "#122738",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_cobalt": {
		CardColor:         "#193549,#0088ff,40,10,100,0,0,100",
		HeadlineFontColor: "#ffc600",
		BodyFontColor:     "#ffffff",
		IconColor:         "#0088ff",
		RankBadgeColor:    "#122738",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"rose_pine": {
		CardColor:         "#191724",
		HeadlineFontColor: "#ebbcba",
		BodyFontColor:     "#e0def4",
		IconColor:         "#c4a7e7",
		RankBadgeColor:    "#1f1d2e",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_rose_pine": {
		CardColor:         "#191724,#c4a7e7,40,10,100,0,0,100",
		HeadlineFontColor: "#ebbcba",
		BodyFontColor:     "#e0def4",
		IconColor:         "#c4a7e7",
		RankBadgeColor:    "#1f1d2e",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"github_dark": {
		CardColor:         "#0d1117",
		HeadlineFontColor: "#58a6ff",
		BodyFontColor:     "#c9d1d9",
		IconColor:         "#7ee787",
		RankBadgeColor:    "#161b22",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_github_dark": {
		CardColor:         "#0d1117,#58a6ff,40,10,100,0,0,100",
		HeadlineFontColor: "#58a6ff",
		BodyFontColor:     "#c9d1d9",
		IconColor:         "#7ee787",
		RankBadgeColor:    "#161b22",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"github_light": {
		CardColor:         "#ffffff",
		HeadlineFontColor: "#0969da",
		BodyFontColor:     "#24292f",
		IconColor:         "#1a7f37",
		RankBadgeColor:    "#f6f8fa",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"material": {
		CardColor:         "#263238",
		HeadlineFontColor: "#80cbc4",
		BodyFontColor:     "#eeffff",
		IconColor:         "#ffcb6b",
		RankBadgeColor:    "#1e272c",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_material": {
		CardColor:         "#263238,#80cbc4,40,10,100,0,0,100",
		HeadlineFontColor: "#80cbc4",
		BodyFontColor:     "#eeffff",
		IconColor:         "#ffcb6b",
		RankBadgeColor:    "#1e272c",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"ayu_dark": {
		CardColor:         "#0a0e14",
		HeadlineFontColor: "#ffb454",
		BodyFontColor:     "#b3b1ad",
		IconColor:         "#e6b450",
		RankBadgeColor:    "#050709",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_ayu_dark": {
		CardColor:         "#0a0e14,#ffb454,40,10,100,0,0,100",
		HeadlineFontColor: "#ffb454",
		BodyFontColor:     "#b3b1ad",
		IconColor:         "#e6b450",
		RankBadgeColor:    "#050709",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"ayu_light": {
		CardColor:         "#fafafa",
		HeadlineFontColor: "#ff6a00",
		BodyFontColor:     "#5c6166",
		IconColor:         "#86b300",
		RankBadgeColor:    "#f0f0f0",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"kanagawa": {
		CardColor:         "#1f1f28",
		HeadlineFontColor: "#dca561",
		BodyFontColor:     "#dcd7ba",
		IconColor:         "#7e9cd8",
		RankBadgeColor:    "#16161d",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_kanagawa": {
		CardColor:         "#1f1f28,#7e9cd8,40,10,100,0,0,100",
		HeadlineFontColor: "#dca561",
		BodyFontColor:     "#dcd7ba",
		IconColor:         "#7e9cd8",
		RankBadgeColor:    "#16161d",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"everforest": {
		CardColor:         "#2d353b",
		HeadlineFontColor: "#a7c080",
		BodyFontColor:     "#d3c6aa",
		IconColor:         "#83c092",
		RankBadgeColor:    "#232a2e",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
	"gradient_everforest": {
		CardColor:         "#2d353b,#a7c080,40,10,100,0,0,100",
		HeadlineFontColor: "#a7c080",
		BodyFontColor:     "#d3c6aa",
		IconColor:         "#83c092",
		RankBadgeColor:    "#232a2e",
		Font:              "Segoe UI, Ubuntu, Sans-Serif",
	},
}
